### ISSUE TITLE
Mostrar listado de los patitos disponibles (Hito - 20 de abril)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-patitopia#1]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo el desarrollo de más funcionalidad.

El menú es bastante básico y deberíais hacerlo para que el menú se repita indefinidamente. 

Tabulad mejor el código para que sea más legible.

El hito que os propongo para el 20 de abril es que creéis un fichero con todos los patos o sus características para que se muestren en la opción correspondiente del menú. Os aconsejo que almacenéis los datos en un vector de estructuras.

Además de esto, os animo a que sigáis programando más funcionalidades.

Un saludo y buenas vacaciones.

**Comment by LnaLR** [comment]
Ya hemos entregado el issue pedido.
